server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog_dev?useUnicode=true&characterEncoding=utf8
  security:
    user:
      name: admin
      password: admin
  redis:
    host: 106.15.184.14
    password: 123456
    port: 6379
    database: 0
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: yjs1320467166@163.com
    #授权码
    password: LTIXICLZNBHPNDWC
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
swagger:
  enable: true
  # activiti default configuration
#activiti:
  #database-schema-update: true
  #check-process-definitions: true
  #process-definition-location-prefix: classpath:/processes/
  #    process-definition-location-suffixes:
  #      - **.bpmn
  #      - **.bpmn20.xml
  #history-level: full
